[[thermometers]]
name = "Diode1"
hardware = "DummyThermometer"
address = "COM5"

[[thermometers]]
name = "Diode2"
hardware = "DummyThermometer"
address = "COM5"

[[heaters]]
name = "Heater1"
hardware = "DummyHeater"
address = "COM5"
max_value = 24

[[heaters]]
name = "Heater2"
hardware = "DummyHeater"
address = "COM5"

