[[thermometers]]
name = '3HEADA'
hardware = 'swarm_lockin'
calibration_file = './config/ROX6951.csv'
interface = '/dev/lockins'
setup.mux_name = '3HEADA'

[[thermometers]]
name = '4HEADA'
hardware = 'swarm_lockin'
calibration_file = './config/ROX6951.csv'
interface = '/dev/lockins'
setup.mux_name = '4HEADA'

[[thermometers]]
name = '3HEADB'
hardware = 'swarm_lockin'
calibration_file = './config/ROX6951.csv'
interface = '/dev/lockins'
setup.mux_name = '3HEADB'

[[thermometers]]
name = '4HEADB'
hardware = 'swarm_lockin'
calibration_file = './config/ROX6951.csv'
interface = '/dev/lockins'
setup.mux_name = '4HEADB'

[[thermometers]]
name = 'DHEAD'
hardware = 'swarm_lockin'
calibration_file = './config/RO600.csv'
interface = '/dev/lockins'
setup.mux_name = 'DHEAD'

[[thermometers]]
name = 'STILL'
hardware = 'swarm_lockin'
calibration_file = './config/RuO2mean.csv'
interface = '/dev/lockins'
setup.mux_name = 'STILL'

[[thermometers]]
name = 'CONDENSER'
hardware = 'swarm_lockin'
calibration_file = './config/RuO2mean.csv'
interface = '/dev/lockins'
setup.mux_name = 'CONDENSER'

[[thermometers]]
name = '4PUMPA'
hardware = 'swarm_diode'
calibration_file = './config/DT670.csv'
interface = '/dev/diodes'
setup.mux_name = '4PUMPA'

[[thermometers]]
name = '4PUMPB'
hardware = 'swarm_diode'
calibration_file = './config/DT670.csv'
interface = '/dev/diodes'
setup.mux_name = '4PUMPB'

[[thermometers]]
name = '3PUMPA'
hardware = 'swarm_diode'
calibration_file = './config/DT670.csv'
interface = '/dev/diodes'
setup.mux_name = '3PUMPA'

[[thermometers]]
name = '3PUMPB'
hardware = 'swarm_diode'
calibration_file = './config/DT670.csv'
interface = '/dev/diodes'
setup.mux_name = '3PUMPB'

[[thermometers]]
name = '4SWITCHA'
hardware = 'swarm_diode'
calibration_file = './config/DT670.csv'
interface = '/dev/diodes'
setup.mux_name = '4SWITCHA'

[[thermometers]]
name = '4SWITCHB'
hardware = 'swarm_diode'
calibration_file = './config/DT670.csv'
interface = '/dev/diodes'
setup.mux_name = '4SWITCHB'


[[thermometers]]
name = '3SWITCHA'
hardware = 'swarm_diode'
calibration_file = './config/DT670.csv'
interface = '/dev/diodes'
setup.mux_name = '3SWITCHA'


[[thermometers]]
name = '3SWITCHB'
hardware = 'swarm_diode'
calibration_file = './config/DT670.csv'
interface = '/dev/diodes'
setup.mux_name = '4SWITCHB'


[[thermometers]]
name = '40K'
hardware = 'swarm_diode'
calibration_file = './config/DT670.csv'
interface = '/dev/diodes'
setup.mux_name = '40K'


[[thermometers]]
name = '4K'
hardware = 'swarm_diode'
calibration_file = './config/DT670.csv'
interface = '/dev/diodes'
setup.mux_name = '4K'


[[heaters]]
name = '4PUMPA'
hardware = 'swarm_hph'
max_value = 30
interface = '/dev/heaters'
setup.mux_name = '4PUMPA'

[[heaters]]
name = '4PUMPB'
hardware = 'swarm_hph'
max_value = 30
interface = '/dev/heaters'
setup.mux_name = '4PUMPB'

[[heaters]]
name = '3PUMPA'
hardware = 'swarm_hph'
max_value = 30
interface = '/dev/heaters'
setup.mux_name = '3PUMPA'

[[heaters]]
name = '3PUMPB'
hardware = 'swarm_hph'
max_value = 30
interface = '/dev/heaters'
setup.mux_name = '3PUMPB'

[[switches]]
name = '4SWITCHA'
hardware = 'swarm_lph'
max_value = 8
interface = '/dev/heaters'
setup.mux_name = '4SWITCHA'

[[switches]]
name = '4SWITCHB'
hardware = 'swarm_lph'
max_value = 8
interface = '/dev/heaters'
setup.mux_name = '4SWITCHB'

[[switches]]
name = '3SWITCHA'
hardware = 'swarm_lph'
max_value = 8
interface = '/dev/heaters'
setup.mux_name = '4SWITCHA'

[[switches]]
name = '3SWITCHB'
hardware = 'swarm_lph'
max_value = 8
interface = '/dev/heaters'
setup.mux_name = '3SWITCHB'

[[switches]]
name = 'STILL'
hardware = 'swarm_lph'
max_value = 8
interface = '/dev/heaters'
setup.mux_name = 'STILL'


