[pre_cool]
temperature_thresholds = {'MAINPLATE'= 6.5, '4HEAD' = 0.875}
heaters = {}
relays = {} 

[start_recycle]
temperature_thresholds = {'4SWITCH'= 10}
heaters = {}
relays = {} 


[get_pump_warm]
temperature_thresholds = {'4PUMP'= 25}
heaters = {'4PUMP' = {pid_set_value = 25, elapse_time_max = 900}}
relays = {} 


[get_pump_hot]
temperature_thresholds = {'4HEAD'= 2.5}
heaters = {'4PUMP' = {pid_set_value = 45, elapse_time_max = 1800}}
relays = {} 


[turn_off_pump]
temperature_thresholds = {}
heaters = {'4PUMP' = {pid_set_value = 0, elapse_time_max = 10}}
relays = {} 

[turn_on_heat_switch_4]
temperature_thresholds = {'4HEAD'= 0.900}
heaters = {}
relays = {'4SWITCH' = {pid_set_value = 22, elapse_time_max = 5400}}

[head_cold]
temperature_thresholds = {}
heaters = {}
relays = {'4SWITCH' = {pid_set_value = 22}}


[misc]
state_machine_cycle_time = 1
start_recycle_temp = 1.75
start_recycle_clock_hour = 6
start_recycle_clock_min = 1

[pid_configuration]
4PUMP = {kp = 10, ki = 1, kd = 0}
4SWITCH = {kp = 10, ki = 1, kd = 0}
    

