services:
  hal:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true  # Grants access to all devices including USB
    volumes:
      - ./config:/app/config/
      - ./logs:/app/logs/
      - /dev/serial:/dev/serial # Allow access to the serial devices
    command: ["python", "sm-1k.py"]
    restart: always

