[constants]
switch_temp = 20


[thermometers]
[thermometers.1k]
corresponding_heater = "4HEAD"
coefficients = {P = 10, I = 1, D = 0}
[thermometers.4k]
corresponding_heater = "4HEAD"
coefficients = {P = 10, I = 1, D = 0}




### States - Set to these values when entering the state
[states]
[states.warm]
4HEAD = 300
PUMP = 300


[[transitions]]
from = "warm"
to = "cold"
max_seconds = 60
criteria = [
    "heat_switch < switch_temp",
    "pump < 50",
]

[[transitions]]
from = "warm"
to = "slightly_warm"
max_seconds = 60
criteria = [
    "heat_switch > 20",
    "pump > 50",
]

[[transitions]]
from = "cold"
to = "warm"
max_seconds = 60
criteria = [
    "heat_switch < 20",
    "pump < 50",
]