[constants]
T_switch_high = 20

# [thermometers.name_of_thermometer]
[thermometers.1k]
corresponding_heater = "4HEAD"
coefficients = {P = 10, I = 1, D = 0}
[thermometers.4k]
corresponding_heater = "4HEAD"
coefficients = {P = 10, I = 1, D = 0}
[thermometers.pump]
corresponding_heater = "PUMPHEATER"
coefficients = {P = 10, I = 1, D = 0}
[thermometers.heat_switch]
corresponding_heater = "HS_HEATER"
coefficients = {P = 10, I = 1, D = 0}



### States - Set to these values when entering the state
[states.warm]
[states.warming_up]
pump = 300
4k = 300
1k = 300
[states.cold]
pump = 300
4k = 300
1k = 300
heat_switch = "T_switch_high"



[[transitions]]
from = "warm"
to = "cold"
max_seconds = 60
criteria = [
    "heat_switch < T_switch_high",
    "pump < 50",
]

[[transitions]]
from = "warm"
to = "slightly_warm"
max_seconds = 60
criteria = [
    "heat_switch > 20",
    "pump > 50",
]

[[transitions]]
from = "cold"
to = "warm"
max_seconds = 60
criteria = [
    "heat_switch < 20",
    "pump < 50",
]