[[thermometers]]
name = "4K"
hardware = "DummyThermometer"
address = "COM5"

[[thermometers]]
name = "1K"
hardware = "DummyThermometer"
address = "COM5"

[[thermometers]]
name = "1K-main-plate"
hardware = "DummyThermometer"
address = "COM5"

[[heaters]]
name = "PUMPHEATER"
hardware = "DummyHeater"
address = "COM5"
max_value = 24

[[heaters]]
name = "HS_HEATER"
hardware = "DummyHeater"
address = "COM5"

